title: Teach, Learn, Make
lang: en
description: Make a Developer's life's easier.

remote_theme: rundocs/jekyll-rtd-theme

addons_branch: true
edit: true

addons:
  - github
  - i18n
  - plugins
  - analytics

copyright:
  revision: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
